export const VERSIONS = [
  {
    version: '2.0',
    date: 'March 21, 2026',
    title: 'The Index — Knowledge Base + Collaboration Overhaul',
    summary: 'New Index page for organizing research into folders and working threads. Index This buttons on every feed post and interview. Meeting creation with participants and scheduling. Pain vs Opportunity scoring replaces old 6-dimension scoring. Major UI polish across all pages.',
    features: [
      'The Index: Notion-meets-Wikipedia knowledge base for organizing research',
      'Folder system with custom icons and colors for categorizing indexed content',
      'Index This buttons on every feed post and interview card',
      'Source linking: indexed entries link back to original feed post or interview',
      'Pin, move, edit, and tag indexed entries',
      'Create a Meeting: participants, email invites, schedule or start now',
      'Meeting feed posts highlighted with purple gradient + participant avatars',
      'File upload on meeting posts for attaching any document type',
      'Pain vs Opportunity scoring (/10) replaces old 6-dimension /30 scoring',
      'Opportunity score on dashboard, interviews list, and feed interview cards',
      'Interviews ranked by opportunity score in list and sidebar',
      'Collapsible AI Summary on interview detail page',
      'Auto-expanding textareas across interview form',
      'Conditional org profile: Manufacturer, Broker, Distributor fields',
      'The Index added to primary navigation',
    ],
  },
  {
    version: '1.9',
    date: 'March 21, 2026',
    title: 'Threaded Conversations, Link Previews, Real-Time Notifications',
    summary: 'Feed becomes a collaboration hub with threaded replies, AI category tags, link previews with thumbnails, an Active Threads sidebar, and real-time notifications via Supabase Realtime.',
    features: [
      'Threaded replies: every post has a reply function with full rich text formatting',
      'Each thread generates a unique shareable link',
      'AI-generated category tags on every new post for database organization',
      'Link previews: posts with URLs show thumbnail, title, and description from the linked page',
      'Active Threads sidebar: live feed of threads with new comments since last visit',
      'Real-time notifications via Supabase Realtime (no more 30s polling)',
      'Reply notifications with push alerts linking directly to the thread',
      'Thread reply count badges on feed posts',
      'Search now includes thread tags',
    ],
  },
  {
    version: '1.8',
    date: 'March 21, 2026',
    title: 'Liquid Glass UI + Fireflies Auto-Join + Meeting Transcription Flow',
    summary: 'Complete design system overhaul to Liquid Glass with frosted glass cards, backdrop blur, geometric glyphs, and refined typography. Fireflies now auto-joins all meetings regardless of creator. Completed meetings auto-post to feed with AI summary.',
    features: [
      'Liquid Glass design: frosted glass cards with backdrop-blur and translucent borders across all pages',
      'Geometric glyphs replace emojis throughout the app',
      'Refined nav: uppercase tracking, glass blur, monospace section labels',
      'Staggered entrance animations and card hover lift effects',
      'Gradient accent borders on cards (blue, green, amber, red, purple)',
      'Fireflies bot auto-joins all Google Meet calls as calendar attendee',
      'Meeting transcription auto-posts to feed with AI summary, duration, and tagged attendees',
      'Interview completion auto-posts to feed with key signals and pain points',
      'Push notifications for both meeting and interview completions',
      'Client-side SWR cache for near-instant page transitions',
    ],
  },
  {
    version: '1.7',
    date: 'March 21, 2026',
    title: 'Native Push Notifications + Ingest Webhook',
    summary: 'Browser push notifications for all new feed posts so you get alerts even when the tab is closed. Plus a generic ingest webhook for posting to the feed from external tools like WhatsApp, Apple Shortcuts, or curl.',
    features: [
      'Native push notifications: OS-level alerts for all new feed posts + @mentions',
      'Service worker: notifications work even when the tab is closed or backgrounded',
      'Auto push registration on login with browser permission prompt',
      'Ingest webhook: POST to /api/webhooks/ingest from any external tool (curl, Shortcuts, Zapier)',
      'Webhook supports auto-classification of post type via Claude',
      'Webhook creates in-app notifications + push notifications automatically',
      'Push subscription management: auto-cleanup of expired subscriptions',
    ],
  },
  {
    version: '1.6',
    date: 'March 17, 2026',
    title: 'Interviews Redesign, Delete, Timeline Navigation',
    summary: 'Interviews page redesigned with timeline sidebar, date grouping, and select-to-delete. Interview scheduler built (staging). Select mode for bulk interview deletion.',
    features: [
      'Interviews page: timeline sidebar with date + interviewee navigation',
      'Interviews grouped by date (upcoming/completed sections)',
      'Select mode: bulk delete interviews with confirmation',
      'Interview scheduler with auto Meet link (staging — hidden for debug)',
      'DELETE endpoint for interviews API',
    ],
  },
  {
    version: '1.5',
    date: 'March 17, 2026',
    title: 'Rich Editor, Mentions, News Room, Automated Meetings',
    summary: 'Rich text editor with inline @mentions that trigger notifications. News Room with live RSS feeds. Automated meeting recording via Fireflies + Google Calendar. Redesigned nav and feed layout.',
    features: [
      'Rich text editor: bold, italic, lists, highlights, code blocks, emoji',
      'Inline @mentions — type @ to tag Wes or Gibb with styled pill bubbles',
      'In-app notifications: badge on profile avatar, mention previews',
      'News Room: live RSS feeds from Food Dive, Grocery Dive, TechCrunch AI, VentureBeat AI + more',
      'News sorted by date with category filters (Industry, Retail, CPG, AI)',
      'Today\'s Big News: top 3 featured articles',
      'Automated meetings: Google Calendar API auto-generates Meet links',
      'Fireflies.ai bot auto-joins calls, webhook auto-posts transcript + AI summary',
      'Whisper audio transcription via Groq (upload recordings to auto-transcribe)',
      'Feed redesign: sticky composer, timeline sidebar, full-width images, search + filters',
      'Expandable FAB: New Post, New Meeting, New Interview from any page',
      'Nav redesign: THE HUB logo, simplified primary tabs + More dropdown',
      'Feed post editing with "last edited" timestamps',
      'Supabase Auth: password-protected login, user profiles (Wes + Gibb)',
    ],
  },
  {
    version: '1.3',
    date: 'March 15, 2026',
    title: 'Meetings, Tasks, Attachments & More',
    summary: 'Meeting scheduling with Google Meet links and transcript capture. Trello-style task board. Interview file attachments with AI parsing for search.',
    features: [
      'Meeting scheduler with Google Meet link generation',
      'Post-meeting transcript upload with AI summary',
      'Trello-style task board with drag-and-drop',
      'Interview file attachments (PDFs, docs, images, audio, video)',
      'Attached files parsed by AI and searchable',
      'Dev changelog',
    ],
  },
  {
    version: '1.2',
    date: 'March 14, 2026',
    title: 'Visual Workflow Flowchart',
    summary: 'Interactive flowchart visualization for interview workflows using React Flow. AI generates the initial map from interview data.',
    features: [
      'AI-generated workflow flowcharts from interview data',
      '6 color-coded node types: workflow step, pain point, friction, opportunity, handoff, system/tool',
      'Drag-and-drop editing with auto-save',
      'Click nodes to see related interview data in detail panel',
      'Minimap and zoom controls',
    ],
  },
  {
    version: '1.1',
    date: 'March 14, 2026',
    title: 'Feed Enhancements, Search & Import',
    summary: 'Major feed upgrade with pinning, archiving, media, and tagging. AI-powered search. Transcript import for interviews.',
    features: [
      'Feed: pinned posts, archive/delete, media uploads, @Wes/@Gibb tagging',
      'Feed: video link embeds (YouTube, Vimeo, Loom)',
      'AI-powered natural language search across full database',
      'Interview transcript import — paste text, AI fills the form',
      'MCP server with 11 tools for Claude Desktop integration',
      'Light theme matching Dropclaw aesthetic',
    ],
  },
  {
    version: '1.0',
    date: 'March 13, 2026',
    title: 'Initial Build',
    summary: 'Core platform with headless API, Supabase database, and 6-view frontend. Deployed to Vercel.',
    features: [
      'Dashboard with stats, opportunity ranking, pain distribution',
      'Feed — shared research channel with 6 post types',
      'Project Sync — session handoffs with key takeaways',
      'Interview capture — 7-section structured form with scoring',
      'Digest — auto and on-demand AI summaries',
      'Headless API with Bearer token auth',
      'Supabase Postgres with 5 tables',
      'Export for Synthesis button',
    ],
  },
]

export const CURRENT_VERSION = VERSIONS[0].version
